#!/usr/bin/env python3
"""Generate infographics/index.html from what is actually on disk (H3768).

Derive-don't-store: scans infographics/*/ directories, reads each directory's
<title>, classifies umbrellas vs catalog singles vs draft variants, and emits
one live index page. --check verifies emitted page matches disk state.

Usage:
    python3 scripts/infographics50/gen_infographics_index.py --emit
    python3 scripts/infographics50/gen_infographics_index.py --check
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INF = ROOT / "infographics"
OUT = INF / "index.html"
MANIFEST = Path(__file__).resolve().parent / "data" / "index_generated.json"

CATALOG_DIR = "sanskrit-infographics-catalog"

# Umbrella series: multi-page story sets (MG 31-08-2026: top section of index).
UMBRELLAS = [
    ("github-sanskrit-story-styles-2026-08-29", "all-styles.html",
     "Сюжет «Сколько слов в санскрите?» в 7 стилях + синька — каждый стиль как отдельная страница-story",
     "1 506 452 статьи · 45 словарей · 8 стилевых обложек"),
    ("github-sanskrit-estate-isometric-2026-08-28", "index.html",
     "Изометрический квартал словарей — то же имение, объёмная подача",
     "RU + EN версии · png/mp4/gif"),
    ("github-sanskrit-blueprint-story-2026-08-29", "index.html",
     "Синька-чертёж словарного квартала — техно-рисунок с размерными линиями",
     "RU + EN версии · png/mp4/gif"),
]

# Draft variants: superseded by richer sibling slugs (MG 31-08-2026: keep live,
# list in the index badged «черновик»). Derived as: published dirs that the
# catalog does NOT link; this list documents the supersession pair for the note.
# suitcases-2026-08-29 vs dict-suitcases-2026-08-29: same «Словари как чемоданы»
# idea, two passes — catalog № 44 links the probe-backed dict-suitcases page.
SUPERSEDED_BY = {
    "case-tracks-2026-08-29": "case-roads-2026-08-29",
    "corpora-beside-2026-08-29": "corpora-side-by-side-2026-08-29",
    "license-lights-2026-08-29": "license-traffic-light-2026-08-29",
    "samasa-wheel-2026-08-29": "samasa-chakram-2026-08-29",
    "science-langs-2026-08-29": "three-languages-2026-08-29",
    "suitcases-2026-08-29": "dict-suitcases-2026-08-29",
}

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)


def dir_title(d: Path) -> str:
    """First <title> among the directory's html files, sorted for stability."""
    for f in sorted(d.glob("*.html")):
        m = TITLE_RE.search(f.read_text(encoding="utf-8", errors="replace"))
        if m:
            return " ".join(m.group(1).split())
    return d.name


def entry_html(href_dir: str, title: str, extra: str = "") -> str:
    return (f'<li><a href="{href_dir}/">{title}</a>'
            f'{f" {extra}" if extra else ""}</li>')


def scan() -> dict:
    dirs = sorted(p for p in INF.iterdir() if p.is_dir())
    catalog_links = set()
    cat_index = INF / CATALOG_DIR / "index.html"
    if cat_index.exists():
        text = cat_index.read_text(encoding="utf-8")
        catalog_links = {
            m.split("/")[0]
            for m in re.findall(r'infographics/([a-z0-9-]+)/', text)
        }
    umb_slugs = {u[0] for u in UMBRELLAS}
    singles, drafts, other = [], [], []
    for d in dirs:
        slug = d.name
        if slug == CATALOG_DIR:
            continue
        title = dir_title(d)
        if slug in umb_slugs:
            continue
        if slug in catalog_links:
            singles.append((slug, title))
        elif slug in SUPERSEDED_BY:
            drafts.append((slug, title, SUPERSEDED_BY[slug]))
        else:
            other.append((slug, title))
    return {
        "dirs": [d.name for d in dirs],
        "catalog_slugs": sorted(catalog_links),
        "singles": singles,
        "drafts": drafts,
        "other": other,
    }


def build_html(scan_result) -> str:
    umb_cards = []
    for slug, link, desc, meta in UMBRELLAS:
        umb_cards.append(
            f'<li><a href="{slug}/{link}">{dir_title(INF / slug)}</a>'
            f'<span class="d">{desc}</span><span class="m">{meta}</span></li>'
        )
    singles = "\n".join(entry_html(s, t) for s, t in scan_result["singles"])
    drafts = "\n".join(
        entry_html(s, t, f'<span class="draft">черновик · заменён <a href="{sb}/">{sb.split("-2026")[0]}</a></span>')
        for s, t, sb in scan_result["drafts"]
    )
    other = "\n".join(entry_html(s, t) for s, t in scan_result["other"])
    other_block = (
        f'\n  <h2>Прочее</h2>\n  <ul>\n{other}\n  </ul>' if other else ""
    )
    return f"""<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<title>Инфографики санскритского архива — живой индекс</title>
<!-- Generated by scripts/infographics50/gen_infographics_index.py --emit (H3768). Do not hand-edit. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@500;600;700&family=Nunito:wght@400;600;700;800&display=swap" rel="stylesheet">
<style>
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
:root {{
  --paper:#F5EFE3; --ink:#29261F; --ink-soft:rgba(41,38,31,.62);
  --accent:#C4552F; --card:#FFFFFF; --hair:rgba(41,38,31,.16); --ok:#2E7D4F;
  --font-display:'Comfortaa',sans-serif; --font-body:'Nunito',sans-serif;
}}
html, body {{ background: var(--paper); }}
body {{ font-family: var(--font-body); color: var(--ink); }}
.wrap {{ max-width: 1080px; margin: 0 auto; padding: 52px 36px 72px; }}
.kicker {{ font: 700 13px/1.4 var(--font-body); letter-spacing: .2em; text-transform: uppercase; color: var(--ink-soft); }}
h1 {{ font-family: var(--font-display); font-weight: 700; font-size: 46px; line-height: 1.1; margin-top: 12px; }}
.standfirst {{ margin-top: 14px; max-width: 820px; font: 400 18px/1.55 var(--font-body); color: var(--ink-soft); }}
h2 {{ font-family: var(--font-display); font-weight: 700; font-size: 24px; margin-top: 44px; padding-bottom: 9px; border-bottom: 3px solid var(--ink); }}
ul {{ margin-top: 14px; display: grid; grid-template-columns: repeat(auto-fill, minmax(330px, 1fr)); gap: 10px; list-style: none; padding: 0; }}
li {{ background: var(--card); border: 1.5px solid var(--hair); border-radius: 10px; padding: 12px 14px; }}
li.umb {{ border-color: var(--ok); border-width: 2px; }}
a {{ color: var(--accent); font-weight: 700; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.d {{ display: block; margin-top: 6px; font: 400 13.5px/1.45 var(--font-body); color: var(--ink-soft); font-weight: 400; }}
.m {{ display: block; margin-top: 6px; font: 600 12px var(--font-body); color: var(--ok); letter-spacing: .04em; }}
.draft {{ display: inline-block; margin-left: 8px; padding: 2px 9px; border-radius: 12px; font: 700 11px var(--font-body); letter-spacing: .04em; background: var(--hair); color: var(--ink-soft); }}
.draft a {{ font-weight: 700; color: var(--ink-soft); }}
footer {{ margin-top: 56px; padding-top: 16px; border-top: 3px solid var(--ink); font: 400 13.5px/1.6 var(--font-body); color: var(--ink-soft); }}
footer a {{ font-weight: 600; }}
</style>
</head>
<body>
<div class="wrap">
  <div class="kicker">Санскритский архив Гасунса · живой индекс инфографик · сгенерировано с диска</div>
  <h1>Все инфографики имения</h1>
  <p class="standfirst">Каждая папка, фактически опубликованная под <b>/infographics/</b>, — серии-«зонтики», страницы каталога 50 идей и черновые варианты. Индекс генерируется скриптом из файлов на диске; статус-каталог идей живёт отдельно: <a href="{CATALOG_DIR}/">каталог 50 инфографик</a>.</p>

  <h2>Серии-«зонтики»</h2>
  <ul>
{chr(10).join(umb_cards)}
  </ul>

  <h2>Инфографики каталога ({len(scan_result["singles"])})</h2>
  <ul>
{singles}
  </ul>

  <h2>Черновые варианты ({len(scan_result["drafts"])})</h2>
  <p class="standfirst">Ранние версии, заменённые более полными страницами; опубликованы и остаются доступны.</p>
  <ul>
{drafts}
  </ul>{other_block}

  <footer>
    <b>Индекс сгенерирован</b> scripts/infographics50/gen_infographics_index.py --emit (H3768) из содержимого infographics/ · {len(scan_result["dirs"])} папок на диске · 31.08.2026 · Dr. Mārcis Gasūns
  </footer>
</div>
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--emit", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not INF.is_dir():
        raise SystemExit(f"infographics/ not found at {INF}")
    res = scan()
    html = build_html(res)

    if args.emit:
        OUT.write_text(html, encoding="utf-8")
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(
            json.dumps(res, ensure_ascii=False, indent=1) + "\n",
            encoding="utf-8",
        )
        print(
            f"index.html written: {len(res['singles'])} catalog singles, "
            f"{len(res['drafts'])} drafts, {len(res['other'])} other, "
            f"{len(res['dirs'])} dirs total"
        )
        return
    # --check
    if not OUT.exists() or OUT.read_text(encoding="utf-8") != html:
        print("check: index.html DRIFTED from disk state — re-run with --emit")
        return 1
    print("check: index.html matches disk state "
          f"({len(res['dirs'])} dirs, {len(res['singles'])} singles, "
          f"{len(res['drafts'])} drafts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())